added support to new display and lvgl
arduino-libraries/Arduino_MKRIoTCarrier pull request #36
Opened 2021-07-26 15:07 UTC by Rocketct

- added support to display with GC9A01 Driver
- added lv_conf.h file to allows for lvgl configuration

for future example add on top header inclusion the lv_conf.h file

2021-07-28 09:09 UTC, alranel requested changes

2021-07-28 09:09 UTC, alranel commented on src/Arduino_MKRIoTCarrier.h
> +    MKRIoTDispalyClass display = MKRIoTDispalyClass();
There's a typo: "Dispaly" should be "Display"

2021-07-28 12:36 UTC, marqdevx approved these changes
LGTM!

2021-09-16 04:25 UTC, aentinger commented
@Rocketct - as far as I can see, we can merge this one, no?

2021-09-16 07:02 UTC, Rocketct commented
ciao Alex unfortunately no, even if this is fine, we shall wait that the new display driver is confirmed

2021-12-15 08:45 UTC, aentinger commented
@Rocketct any update if this has been validated with the new display driver?

2022-08-18 07:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_MKRIoTCarrier?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_MKRIoTCarrier?pullRequest=36) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: giulcioffi<br/>:white_check_mark: Rocketct<br/>:x: maidnl<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_MKRIoTCarrier?pullRequest=36) it.</sub>

2022-10-13 10:30 UTC, closed without merging