added Air quality and imperial quantities
arduino-libraries/Arduino_MKRIoTCarrier pull request #60
Opened 2022-10-19 13:47 UTC by Rocketct

2022-10-19 13:50 UTC, facchinm requested changes

2022-10-19 13:50 UTC, facchinm commented on src/EnvClass.cpp
> +      reading = iaqSensor->temperature;
Can remove this line

2022-10-19 13:50 UTC, facchinm commented on src/PressureClass.cpp
> +      reading = iaqSensor->temperature;
can remove this too

2022-10-19 14:37 UTC, Rocketct commented on src/PressureClass.cpp
> +      reading = iaqSensor->temperature;
done

2022-10-19 14:37 UTC, Rocketct commented on src/EnvClass.cpp
> +      reading = iaqSensor->temperature;
done

2022-10-19 15:35 UTC, facchinm requested changes

2022-10-19 15:35 UTC, facchinm commented on src/AirQualityClass.cpp
> +  //If board_revision = 1, IMU module is LSM6DSOX, otherwise is LSM6DS3
Need to fix some stray comment

2022-10-19 15:35 UTC, facchinm commented on src/AirQualityClass.cpp
> +  This file is part of the Arduino_LSM6DSOX library.
Change this to the correct name

2022-10-20 12:26 UTC, Rocketct commented on src/AirQualityClass.cpp
> +  //If board_revision = 1, IMU module is LSM6DSOX, otherwise is LSM6DS3
removed make sense only in IMUCLass

2022-10-20 12:26 UTC, Rocketct commented on src/AirQualityClass.cpp
> +  This file is part of the Arduino_LSM6DSOX library.
changed also in IMUCLass :)

2022-10-20 12:27 UTC, Rocketct commented on src/AirQaulityClass.cpp
> +AirQaulityClass::AirQaulityClass( getRev_t getRevision)
fixed

2022-10-20 13:21 UTC, facchinm approved these changes

2022-10-20 13:21 UTC, merged